name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/vidsave

            if [ -f package-lock.json ]; then
              cp package-lock.json package-lock.json.old
            fi

            git pull origin main

            if [ -f package-lock.json.old ] && ! cmp -s package-lock.json.old package-lock.json; then
              echo "package-lock.json"
              rm -rf node_modules
              npm ci --omit=dev
            else 
              echo "package-lock.json"
            fi

            rm -rf .next/

            npm run build

            pm2 delete all || true
            
            pm2 start npm --name "vidsaveStart" -- run start

            rm -f package-lock.json.old